litrevu/litrevu/urls.py
from django.contrib import admin
from django.urls import path
import authentication.views
import appli.views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', authentication.views.login_view, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('signup/', authentication.views.signup_page, name='signup'),
    path('flux/', appli.views.flux, name='flux'),
    path('ticket/', appli.views.create_ticket, name='ticket'),
    path('ticket/<int:ticket_id>/edit/', appli.views.edit_ticket, name='edit_ticket'),
    path('ticket/<int:ticket_id>/delete/', appli.views.delete_ticket, name='delete_ticket'),
    path('review/', appli.views.create_review, name='review'),
    path('review/<int:review_id>/edit/', appli.views.edit_review, name='edit_review'),
    path('review/<int:review_id>/delete/', appli.views.delete_review, name='delete_review'),
    path('response/<int:ticket_id>/', appli.views.create_response, name='response'),
    path('post_list/', appli.views.post_list, name='post_list'),
    path('subscriptions/', appli.views.check_user_to_follow, name='subscriptions'),
    path('subscriptions/<int:user_follows_id>/delete/', appli.views.delete_following,
         name='delete_following'),
    ]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

litrevu/appli/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    # Your Ticket model definition goes here
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    # Your UserFollows model definition goes here
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='followed_by')

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user')

litrevu/appli/forms.py
from django import forms
from . import models


class TicketForm(forms.ModelForm):
    class Meta:
        model = models.Ticket
        fields = ['title', 'description', 'image']


class ReviewForm(forms.ModelForm):
    RATING_CHOICES = [
        (0, '0'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    ]

    rating = forms.ChoiceField(
        choices=RATING_CHOICES,
        widget=forms.RadioSelect(),
        label='Rating'
    )

    class Meta:
        model = models.Review
        fields = ['headline', 'rating', 'body']
        widgets = {
            'rating': 'Note',
            'body': forms.Textarea(attrs={'rows': 4, 'cols': 60}),
        }


class UserToFollowForm(forms.Form):
    user_to_follow = forms.CharField(
        error_messages={'required': ''},  # Message vide pour l'erreur 'required'
    )


class UserFollowedForm(forms.Form):
    user_followed = forms.Textarea(attrs={'rows': 1, 'cols': 60})


class FollowersForm(forms.Form):
    followers = forms.Textarea(attrs={'rows': 1, 'cols': 80})

litrevu/appli/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from itertools import chain
from functools import wraps
import os
from . import forms, models
from authentication.models import User
from appli.models import UserFollows


# décorateur pour limiter les modifications ou suppression
# de ticket au créateur du ticket
def is_ticket_owner(view_func):
    @wraps(view_func)
    def wrapper(request, ticket_id, *args, **kwargs):
        from .models import Ticket  # Import à l'intérieur pour éviter les imports circulaires

        ticket = get_object_or_404(Ticket, id=ticket_id)

        if ticket.user == request.user:
            return view_func(request, ticket_id, *args, **kwargs)
        else:
            return redirect('flux')
    return wrapper


# décorateur pour limiter les modifications ou suppression
# de riview au créateur de la review
def is_review_owner(view_func):
    @wraps(view_func)
    def wrapper(request, review_id, *args, **kwargs):
        from .models import Review  # Import à l'intérieur pour éviter les imports circulaires

        review = get_object_or_404(Review, id=review_id)

        if review.user == request.user:
            return view_func(request, review_id, *args, **kwargs)
        else:
            return redirect('flux')
    return wrapper


def ticket_has_review(view_func):
    @wraps(view_func)
    def wrapper(request, ticket_id, *args, **kwargs):

        reviewed = models.Review.objects.filter(ticket_id=ticket_id).values_list('ticket', flat=True)

        if reviewed:
            return redirect('flux')
        else:
            return view_func(request, ticket_id, *args, **kwargs)
    return wrapper


@login_required
def flux(request):
    current_user = request.user
    tickets = models.Ticket.objects.all()
    reviews = models.Review.objects.all()

    followed = models.UserFollows.objects.filter(user=current_user).values_list('followed_user', flat=True)

    tickets = models.Ticket.objects.filter(
        Q(user=current_user) |  # Tickets créés par l'utilisateur connecté
        Q(user__in=followed)  # OU créés par les utilisateurs suivis
    )

    reviews = models.Review.objects.filter(
        Q(user=current_user) |  # Reviews créés par l'utilisateur connecté
        Q(user__in=followed) |  # OU créées par les utilisateurs suivis
        Q(ticket__user=current_user)  # OU dont le ticket a été créé par l'utilisateur connecté
    )

    # on fusionne les listes en posts et on les trie par ordre antichronologique
    posts = list(chain(tickets, reviews))
    posts.sort(key=lambda x: x.time_created, reverse=True)

    context = {
        'posts': posts,
    }
    return render(request, 'appli/flux.html', context=context)


@login_required
def post_list(request):
    current_user = request.user
    tickets = models.Ticket.objects.all()
    reviews = models.Review.objects.all()

    tickets = models.Ticket.objects.filter(
        Q(user=current_user)   # Tickets créés par l'utilisateur connecté
    ).order_by('-time_created')

    reviews = models.Review.objects.filter(
        Q(user=current_user)   # Reviews crééss par l'utilisateur connecté

    ).order_by('-time_created')

    posts = list(chain(tickets, reviews))
    posts.sort(key=lambda x: x.time_created, reverse=True)

    context = {
        'posts': posts,
    }
    return render(request, 'appli/post_list.html', context=context)


@login_required
def create_ticket(request):
    ticket_form = forms.TicketForm()
    if request.method == 'POST':
        # handle the POST request here
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        if (ticket_form.is_valid()):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket_form.save()

            return redirect('flux')

    context = {
        'ticket_form': ticket_form,
        'message': "Créer un ticket",
    }
    return render(request, 'appli/create_ticket.html', context=context)


@login_required
@is_ticket_owner
def edit_ticket(request, ticket_id):
    ticket_form = forms.TicketForm()
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    if ticket.user == request.user:
        ticket_form = forms.TicketForm(instance=ticket)
        if request.method == 'POST':
            # handle the POST request here
            ticket_form = forms.TicketForm(request.POST, request.FILES, instance=ticket)
            if (ticket_form.is_valid()):
                ticket = ticket_form.save(commit=False)
                ticket.user = request.user
                ticket_form.save()

                return redirect('post_list')

        context = {
            'ticket_form': ticket_form,
            'message': "Modifier le ticket",
        }
        return render(request, 'appli/create_ticket.html', context=context)
    else:
        return redirect('flux')


@login_required
@is_ticket_owner
def delete_ticket(request, ticket_id):
    ticket = models.Ticket.objects.get(id=ticket_id)

    if request.method == 'POST':
        if ticket.image:
            if os.path.isfile(ticket.image.path):
                os.remove(ticket.image.path)
        # handle the POST request here
        ticket.delete()
        return redirect('flux')

    return render(request, 'appli/delete_ticket.html', {'ticket': ticket})


# Créer un ticket et une review associée
# puis les sauvegarder
@login_required
def create_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        # handle the POST request here
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            ticket.save()
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = ticket
            review.save()

            return redirect('flux')

    context = {
        'ticket_form': ticket_form,
        'review_form': review_form,
    }
    return render(request, 'appli/create_review.html', context=context)


@login_required
@is_review_owner
def edit_review(request, review_id):
    review = models.Review.objects.get(id=review_id)
    ticket = get_object_or_404(models.Ticket, id=review.ticket_id)
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        # handle the POST request here
        review_form = forms.ReviewForm(request.POST, )
        if (review_form.is_valid()):
            review = review_form.save(commit=False)
            review.user = request.user
            review.rating = int(review_form.cleaned_data['rating'])
            review.ticket = ticket
            review.save()
            return redirect('flux')

    context = {
        'ticket': ticket,
        'review_form': review_form,
        'message': "Modifier votre critique",
    }
    return render(request, 'appli/create_response.html', context=context)


@login_required
@is_review_owner
def delete_review(request, review_id):
    review = models.Review.objects.get(id=review_id)

    if request.method == 'POST':
        # handle the POST request here
        review.delete()
        return redirect('flux')

    return render(request, 'appli/delete_review.html', {'review': review})


# Créer une review en réponse à un ticket
@login_required
@ticket_has_review
def create_response(request, ticket_id):
    ticket = get_object_or_404(models.Ticket, id=ticket_id)
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        # handle the POST request here
        review_form = forms.ReviewForm(request.POST, )
        if (review_form.is_valid()):
            review = review_form.save(commit=False)
            review.user = request.user
            review.rating = int(review_form.cleaned_data['rating'])
            review.ticket = ticket
            review.save()
            return redirect('flux')

    context = {
        'ticket': ticket,
        'review_form': review_form,
        'message': "Créer une critique",
    }
    return render(request, 'appli/create_response.html', context=context)


@login_required
def check_user_to_follow(request):
    message = ""
    form = forms.UserToFollowForm(request.POST)
    user_follows = models.UserFollows()
    if request.method == 'POST':
        if form.is_valid():
            user_to_follow = form.cleaned_data['user_to_follow']
            resultats = User.objects.filter(username__icontains=user_to_follow)
            #  si l'utilisateur existe
            if resultats:
                target_user = resultats[0]  # Récupérer l'objet User
                # Vérifier si l'utilisateur suit déjà cette personne
                already_following = UserFollows.objects.filter(
                    user=request.user,
                    followed_user=target_user
                ).exists()
                if not already_following:
                    user_follows.user = request.user
                    user_follows.followed_user = target_user
                    user_follows.save()
                else:
                    message = "vous suivez déjà cet utilisateur"
            else:
                message = "Utilisateur non trouvé"
    followed_users = UserFollows.objects.filter(user=request.user)
    followers = User.objects.filter(
        id__in=request.user.followed_by.all().values_list('user', flat=True)
    )

    context = {
        'form': form,
        'followed_users': followed_users,
        'followers': followers,
        'message': message,

    }
    return render(request, 'appli/subscriptions.html', context=context)


@login_required
def delete_following(request, user_follows_id):
    following = models.UserFollows.objects.get(id=user_follows_id)

litrevu/appli/templates/appli/create_critic.html
{% extends 'base.html' %}
{% block content %}
    <h2>Écrire un billet</h2>
    <form method="post" enctype="multipart/form-data">
        {{ ticket_form.as_p }}
        {{ critic_form.as_p }}
        {% csrf_token %}
        <button type="submit" >Publier</button>
    </form>
{% endblock content %}

litrevu/appli/templates/appli/create_response.html
{% extends 'base_connected.html' %}

{% block content %}

    <div class="center">
        <h2>{{ message }}</h2>
    </div>

    <div class="div_border_internal">
        <p><h3>Vous êtes en train de poster en réponse à</h3></p>

        <form method="post" enctype="multipart/form-data">

            <div class="div_border_internal">
                <p>{{ ticket.user.username }} a demandé une critique</p>
                <p class="align-date-right"><i>{{ ticket.time_created }}</i></p>
                <p>{{ ticket.title }}</p>
                <p>{{ ticket.description }}</p>
                {% if ticket.image %}
                    <img src="/media/{{ticket.image}}" alt="image">
                {% endif %}
            </div>

            <div>
                <p><h3>Critique</h3></p>
                <div>
                    <label>Titre</label>
                    <p>{{ review_form.headline }}</p>
                </div>
                
                <div id="id_rating" class="inline">
                    <span>Note</span>
                        <label for="id_rating_0"><input type="radio" name="rating" value="0" required="" id="id_rating_0">
                    0</label>
                        <label for="id_rating_1"><input type="radio" name="rating" value="1" required="" id="id_rating_1">
                    1</label>    
                        <label for="id_rating_2"><input type="radio" name="rating" value="2" required="" id="id_rating_2">
                    2</label>     
                        <label for="id_rating_3"><input type="radio" name="rating" value="3" required="" id="id_rating_3">
                    3</label>                  
                        <label for="id_rating_4"><input type="radio" name="rating" value="4" required="" id="id_rating_4">
                    4</label>
                        <label for="id_rating_5"><input type="radio" name="rating" value="5" required="" id="id_rating_5">
                    5</label>
                </div>
                
                <div>
                    <p>Commentaire</p>
                    <p>{{ review_form.body }}</p>
                </div>
            </div>

            {% csrf_token %}
            <button type="submit" class="button">Publier</button>
        </form>

    </div>
{% endblock content %}

litrevu/appli/templates/appli/create_review.html
{% extends 'base_connected.html' %}

{% block content %}

    <div class="center">
        <h2>Créer une critique</h2>
    </div>

    <div class="div_border_internal">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div>
                <p>Livre / Article</p>
                <p>Titre</p>
                {{ ticket_form.title }}
                <p>Description</p>
                {{ ticket_form.description}}
                <p>Image</p>
                {{ ticket_form.image}}
            </div>
            
            <div>
                <h3>Critique</h3>
                <div>
                    <label>Titre</label>
                    <p>{{ review_form.headline }}</p>
                </div>
                
                <div id="id_second-rating" class="inline">
                    <span>Note</span>
                    {% for radio in review_form.rating %}
                        <label for="{{ radio.id_for_label }}">{{ radio.tag }}
                        {{ radio.choice_label }}</label>
                    {% endfor %}
                </div>
                
                <div>
                    <p>Commentaire</p>
                    <p>{{ review_form.body }}</p>
                </div>
            </div>

            <button type="submit" class="button">Publier</button>
        </form>
    </div>

{% endblock content %}

litrevu/appli/templates/appli/create_ticket.html
{% extends 'base_connected.html' %}

{% block content %}

    <div class="div_border_internal">
        <form method="post" enctype="multipart/form-data">
            <h2 class="center">{{ message }}</h2>
            <label>Titre</label>
            <p>{{ ticket_form.title }}</p>
            <label>Description</label>
            <p>{{ ticket_form.description }}</p>
            <label>Image</label>
            <p>{{ ticket_form.image }}</p>
            {% csrf_token %}
            <button type="submit" class="button">Publier</button>
        </form>
    </div>

{% endblock content %}

litrevu/appli/templates/appli/delete_following.html
{% extends 'base_connected.html' %}

{% block content %}

    <div class="div_margins">
        <p><h1>Ne plus suivre : {{ following.followed_user.username }} ?</h></p>

        <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer" class="button">
        </form>
    </div>

    {% endblock content %}

litrevu/appli/templates/appli/delete_review.html
{% extends 'base_connected.html' %}

{% block content %}

    <div class="div_margins">

        <h1>Supprimer une critique</h1>

        <p>Etes-vous sûr de vouloir supprimer la critique : {{ review.headline }} ?</p>

        <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer" class="button">
        </form>
        
    </div>

{% endblock content %}

litrevu/appli/templates/appli/delete_ticket.html
{% extends 'base_connected.html' %}

{% block content %}

    <div class="div_margins">
        <h1>Supprimer un ticket</h1>

        <p>Etes-vous sûr de vouloir supprimer le ticket : {{ ticket.title }} ?</p>

        <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer" class="button">
        </form>
    </div>

{% endblock content %}

litrevu/appli/templates/appli/flux.html
{% extends 'base_connected.html' %}
{% load custom_filters %}


{% block content %}

    <div class="div_margins div_flex">
        <a href="{% url 'ticket' %}" class="large_button">Demander une critique</a>
        <a href="{% url 'review' %}" class="large_button">Créer une critique</a>
    </div>

    {% for post in posts %}
        <div class="div_border">
            {% if post|get_class == 'Ticket' %}
                <p>{{ post.user.username }} a demandé une critique</p>
                <p class="align-date-right"><i>{{ post.time_created }}</i></p>
                <p>{{ post.title }}</p>
                <p>{{ post.description }}</p>
                {% if post.image %}
                    <img src="/media/{{post.image}}" alt="image">
                {% endif %}
                <div class="align-right">
                    <a href="{% url 'response' post.id %}" class="button">Créer une critique</a>
                </div>
            {% elif post|get_class == 'Review' %}
                <p>{{ post.user.username }} a posté une critique</p>
                <p class="align-date-right"><i>{{ post.time_created }}</i></p>
                <div class="rating-container">
                    <span><h3 class="h3-margin-right">{{ post.headline }} - </h3></span>
                    {% for i in "12345" %}
                        {% if forloop.counter <= post.rating %}
                            <span class="star filled">★</span>
                        {% else %}
                            <span class="star empty">★</span>
                        {% endif %}
                    {% endfor %}
                </div>
                <p>{{ post.body }}</p>
                <div class="div_border_internal">
                    <p>Ticket - {{ post.ticket.user.username }}</p>
                    <p>{{ post.ticket.title }}</p>
                    {% if post.ticket.image %}
                        <img src="/media/{{post.ticket.image}}" alt="image">
                    {% endif %}
                </div>
            {% endif %}
        </div>
    {% endfor %}

{% endblock content %}

litrevu/appli/templates/appli/post_list.html
{% extends 'base_connected.html' %}
{% load custom_filters %}

{% block content %}

    <div class="center">
        <h1>Mes posts</h1>
    </div>

    {% for post in posts %}
        {% if post|get_class == 'Ticket' %}
            <div class="div_border">
                <p>Vous avez publié un ticket</p>
                <p>{{ post.title }}</p>
                <p class="align-date-right"><i>{{ post.time_created }}</i></p>
                <p>{{ post.description }}</p>
                {% if post.image %}
                    <img src="/media/{{post.image}}" alt="image">
                {% endif %}
                <div class="align-right">
                    <a href="{% url 'edit_ticket' post.id %}" class="button">Modifier</a>
                    <a href="{% url 'delete_ticket' post.id %}" class="button">Supprimer</a>
                </div>
            </div>
        {% elif post|get_class == 'Review' %}
            <div class="div_border">
                <p>Vous avez publié une critique</p>
                <div class="rating-container">
                    <span><h3 class="h3-margin-right">{{ post.headline }} - </h3></span>
                    {% for i in "12345" %}
                        {% if forloop.counter <= post.rating %}
                            <span class="star filled">★</span>
                        {% else %}
                            <span class="star empty">★</span>
                        {% endif %}
                    {% endfor %}
                </div>
                <p class="align-date-right"><i>{{ post.time_created }}</i></p>
                <p>{{ post.body }}</p>
                <div class="div_border_internal"> 
                    <p>Ticket - {{ post.ticket.user.username }}</p>
                    <p>{{ post.ticket.title }}</p>
                    <p>{{ post.ticket.description }}</p>
                    {% if post.image %}
                        <img src="/media/{{post.image}}" alt="image">
                    {% endif %}
                </div>
                <div class="align-right">
                    <a href="{% url 'edit_review' post.id %}" class="button">Modifier</a>
                    <a href="{% url 'delete_review' post.id %}" class="button">Supprimer</a>
                </div>
            </div>
            
        {% endif %}
    {% endfor %}

{% endblock content %}

litrevu/appli/templates/appli/subscriptions.html
{% extends 'base_connected.html' %}
{% block content %}
    <div class="div_margins">
        <h2><p>Suivre d'autres utilisateurs</p></h2>
        <form method="post">
            <p>{{ form.user_to_follow }} {{ message }}</p>
            {% csrf_token %}
            <button type="submit" class="button">Envoyer</button>
        </form>
    </div>
    <div class="div_margins">
        <h2>Abonnements</h2>
        {% for instance in followed_users %}
            <div class="div_table_border">
                <div>
                    <h3>{{ instance.followed_user.username }}</h3>
                </div>
                <div>
                    <a href="{% url 'delete_following' instance.id %}" class="button">Supprimer</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="div_margins">
        <h2>Abonnés</h2>
        {% for instance in followers %}
            <div class="div_table_border">
                <h3>{{ instance.username }}</h3>
            </div>
        {% endfor %}
    </div>
    
{% endblock content %}